name: Build and Compile Arduino Code

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the runner OS if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        export PATH="$HOME/bin:$PATH"
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Arduino code
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 /github/workspace/ChatGPTxESP32_1/ChatGPTxESP32_1.ino

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-code
        path: ${{ github.workspace }}/ChatGPTxESP32_1/.build/esp32/esp32/ChatGPTxESP32_1.ino.bin
