name: Build and Compile Arduino Code

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the runner OS if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino@v1

    - name: Compile Arduino code
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 ChatGPTxESP32_1

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-code
        path: ${{ github.workspace }}ChatGPTxESP32_1/.build/esp32/esp32/ChatGPTxESP32_1.bin

